### ISSUE TITLE
Auto-Update with restart=always

### ISSUE THREAD

**Issue by devenbj** [aptalca/docker-ha-bridge#6]
I had been using this docker on my Synology and it worked great. I am in process of migrating to a full PC to take over. It's running Ubuntu 16.04. One minor issue... the Docker container I've created starts before the network is running. It doesn't seem that there is a command to delay the starting of containers. Anything that could be added to this docker-ha-bridge image to loop for network availability? Perhaps have it check 30 times, with a 1 second delay. Once good, proceed... else just start the jar without attempting auto-update.

My testing: Installed. Worked great. Rebooted. Docker indicated it was running. No access. Restarted container using UIFD. HA Bridge worked. Looked at logs. Complaining about inability to resolve github.com. Removed container. Re-added with "version" environment variable defined. Now works flawlessly over reboot. However, it won't auto-update anymore.

**Comment by aptalca** [comment]
I have been thinking about this, but it is really an issue with how the docker service is started.

It really needs to be fixed on the docker side, anything I would try to do within the container would be beyond the scope of this project.

Docker service should wait for network availability because docker itself relies on pulling images from the internet

**Comment by aptalca** [comment]
Another fix would be to use systemd or another service to start the container rather than relying on restart=always. And that service can be configured to wait for network availability before starting the container
