### ISSUE TITLE
Starting on Ubuntu 15.x

### ISSUE THREAD

**Issue by id628** [aptalca/docker-ha-bridge#8]
I had two problems that took me some time to work through as being new to Docker:

I had to replace **-v /etc/localtime:/etc/localtime:ro** with **-e TZ="America/New_York"** because I kept getting _mv: cannot move '/etc/localtime.dpkg-new' to '/etc/localtime': Device or resource busy_

I couldn't get it to start on port 80 - even though I started the container as root, the task inside the container doesn't get root privileges? So I started it on a high port and forwarded it back on Ubuntu main:
**iptables -t nat -I PREROUTING -p tcp --dport 80 -j REDIRECT --to-port**

Could you add this to the README?

**Comment by aptalca** [comment]
Thanks for letting me know. I tested port 80 a while back and it had worked, but I guess the java app was running as root, then. I since changed it to run as user nobody to make it safer and more secure, but I guess the security also prevents port 80 binding. I pushed an update to make it run as root again.

With regards to /etc/localtime, I added that bit about setting TZ to other containers but I guess not this one. I'll go ahead and add it.
